// <auto-generated />
namespace BusinessPermit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Payments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Payments));
        
        string IMigrationMetadata.Id
        {
            get { return "201704260330240_Payments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
